version: '2.0'
services:

  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: {{ cookiecutter.project_slug }}
      POSTGRES_USER: {{ cookiecutter.project_slug }}
      POSTGRES_PASSWORD: insecure
    volumes:
      - ~/.ssh/datapunt.key:/root/.ssh/datapunt.key
      - ./backups:/tmp/backups

  api:
    build: ./api
    ports:
      - "8001:8001"
    links:
      - database
    environment:
      - SECRET_KEY=insecure
      - DB_NAME={{ cookiecutter.project_slug }}
      - DB_PASSWORD=insecure
      - DJANGO_SETTINGS_MODULE={{ cookiecutter.project_slug }}.settings.development
      - UWSGI_HTTP=0.0.0.0:8001
      - UWSGI_MASTER=1
      - UWSGI_STATIC_INDEX=index.html
      - UWSGI_STATIC_MAP=/{{ cookiecutter.project_slug }}/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE={{ cookiecutter.project_slug }}.wsgi:application
    command: uwsgi --py-auto-reload=1
{% if cookiecutter.rabbitmq_enabled == 'True' %}
  rabbit:
    image: rabbitmq:3
    ports:
    - "5672:5672"
    environment:
    - RABBITMQ_ERLANG_COOKIE=SECRET_COOKIE
    - RABBITMQ_DEFAULT_USER={{ cookiecutter.project_slug }}
    - RABBITMQ_DEFAULT_PASS=insecure
    - RABBITMQ_DEFAULT_VHOST=vhost
{% endif %}{% if cookiecutter.celery_enabled == 'True' %}
  celery:
    build: ./api
    links:
      - database
      - rabbit
    environment:
      - SECRET_KEY=insecure
      - DB_NAME={{ cookiecutter.project_slug }}
      - DB_PASSWORD=insecure
      - DJANGO_SETTINGS_MODULE={{ cookiecutter.project_slug }}.settings.development
    volumes:
      - ./api/src:/app
      - ./api/deploy:/deploy
    command: celery -A {{ cookiecutter.project_slug }} worker -l info

  celery_beat:
    build: ./api
    links:
      - database
      - rabbit
    environment:
      - SECRET_KEY=insecure
      - DB_NAME={{ cookiecutter.project_slug }}
      - DB_PASSWORD=insecure
      - DJANGO_SETTINGS_MODULE={{ cookiecutter.project_slug }}.settings.development
    volumes:
      - ./api/src:/app
      - ./api/deploy:/deploy
    command: celery -A {{ cookiecutter.project_slug }} beat -l info --pidfile /tmp/celerybeat.pid
{% endif %}